name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '@ekilz/react-utils@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with:
          version: 6
          run_install: true
      - uses: actions/setup-node@master
        with:
          node-version: 14
          cache: pnpm
      - run: pnpm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
