name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '@ekilz/react-utils@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with:
          version: 6
      - uses: actions/setup-node@master
        with:
          node-version: 14
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: echo '//registry.npmjs.org/:_authToken={NPM_TOKEN}' > .npmrc
      - run: pnpm publish --access public --no-git-check
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
